name: Upload SSB URL

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新为 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新为 v4
        with:
          python-version: '3.11'  # 根据需要修改 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖库，可以指定

      - name: Run script
        run: |
          python ssb_url.py  # 替换为你的 Python 脚本名称
          echo "Script executed successfully."

      - name: Print ssb_url.txt content
        run: |
          if [ -f ssb_url.txt ]; then
            cat ssb_url.txt
          else
            echo "ssb_url.txt does not exist."
            exit 1
          fi

      - name: Check git status
        run: |
          git status

      - name: Check if ssb_url.txt has content
        run: |
          if [ -s ssb_url.txt ]; then
            echo "ssb_url.txt exists and has content."
          else
            echo "ssb_url.txt is empty or does not exist."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --local user.name "andadmadm"
          git config --local user.email "andadmadm@yandex.com"

      - name: Commit and push ssb_url.txt
        run: |
          git add -A  # 强制添加所有更改
          git commit -m "Add ssb_url.txt with the latest URL" || echo "Nothing to commit"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
