name: Upload SSB URL

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新为 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新为 v4
        with:
          python-version: '3.11'  # 根据需要修改 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖库，可以指定

      - name: Run script
        run: |
          python ssb_url.py  # 替换为你的 Python 脚本名称

      - name: Upload ssb_url.txt
        uses: actions/upload-artifact@v3  # 更新为 v3
        with:
          name: ssb-url
          path: ssb_url.txt  # 指定要上传的文件

      - name: List files in the working directory
        run: |
          ls -la  # 列出当前目录中的所有文件

      - name: Check if ssb_url.txt exists
        run: |
          if [ -f ssb_url.txt ]; then
            echo "ssb_url.txt exists."
          else
            echo "ssb_url.txt does not exist."
          fi

