name: Upload SSB URL

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新为 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新为 v4
        with:
          python-version: '3.11'  # 根据需要修改 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖库，可以指定

      - name: Run script
        run: |
          python ssb_url.py  # 替换为你的 Python 脚本名称

      - name: Configure Git
        run: |
          git config --local user.name "andadmadm"
          git config --local user.email "andadmadm@yandex.com"

      - name: Commit and push ssb_url.txt
        run: |
          git add ssb_url.txt
          git commit -m "Add ssb_url.txt with the latest URL"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # 使用 GitHub 提供的 token

